import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";

export const getServerSideProps = withIronSessionSsr(
  async function getServerSideProps({ req }) {
    const user = req.session.user;
    const props = {};
    if (user) {
      props.user = req.session.user;
      props.isLoggedIn = true;
    } else {
      props.isLoggedIn = false;
    }
    return { props };
  },
  sessionOptions
);

export default function Home(props) {
  const router = useRouter();
  const logout = useLogout();
  return (
    <div className={styles.container}>
      <Head>
        <title>Budget Bud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/budgetbudlogo.png" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.main}>
        <div className={`${styles.hero} ${styles.welcome}`}>
          <h1 className={styles.title}>
            Welcome to Budget Bud!
          </h1>
          <p className={styles.description}>
          Budget Bud is a personal budgeting app that makes the daunting task of largescale budgeting easy!
          Budget Bud provides an easy-to-use interface that allows users to log and organize budget entries. Features of the app include the ability to log savings and expenses, display of the user’s total budget, and the ability to further organize budget by customizing subsections of budget entries.
          </p>
        </div>

        <div className={styles.grid}>
          {props.isLoggedIn ? (
            <>
              <Link href="/dashboard" className={styles.card}>
                <h2>Dashboard &rarr;</h2>
                <p>This page is only visible if you are logged in.</p>
              </Link>
              <div
                onClick={logout}
                style={{ cursor: "pointer" }}
                className={styles.card}
              >
                <h2>Logout &rarr;</h2>
                <p>Click here to log out.</p>
              </div>
            </>
          ) : (
            <>
              <Link href="/login" className={styles.card}>
                <h2>Login &rarr;</h2>
                <p>Visit the login page.</p>
              </Link>

              <Link href="/signup" className={styles.card}>
                <h2>Create Account &rarr;</h2>
                <p>Create an account.</p>
              </Link>
            </>
          )}
          <p className={styles.callToAction}>
            Log in or sign up to access your personal budget dashboard and start growing today!
          </p>
          <div className={styles.backgroundInfo}>
            <h2 className={styles.title}>
              About Budget Bud
            </h2>
            <p className={styles.description}>
              Budget Bud aims to make budgeting easy by offering a straightforward budget tracker that allows users to set a total budget for themselves, as well as log savings and expenses.
            </p>
            <p className={styles.description}>
            While other budget applications contain an overabundance of confusing and unnecessary information, Budget Bud goes back to the basics. Simple features that include setting/editing a total budget and adding expenses and savings that effect it create a straightforward user experience.
            </p>
            <h2 className={styles.title}>
              Our Mission
            </h2>
            <p className={styles.description}>
              The goal of Budget Bud is to create an application that makes the daunting task of budgeting something that anyone can take on.  Prioritizing simplicity, accessibility, and design appeal, Budget Bud’s objective is to make logging and organizing budgeting as stress-free as possible.
            </p>
            <div class="center-container">
            <Image
              src="/moneygrowing.jpeg"
              width={300}
              height={300}
              alt="Hands holding a plant sprouting with money"
              style={{
                width: "100%",
                height: "auto",
                objectFit: "contain",
              }}
            />
            </div>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p className={styles.footerLogo}>
          Budget Bud
          <span className={styles.logo}>
            <Image src="/budgetbudlogo.png" alt="Budget Bud Logo" width={25} height={28} />
          </span>
        </p>
      </footer>
    </div>
  );
}