import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Signup(props) {
  const router = useRouter();
  const [
    { username, password, "confirm-password": confirmPassword },
    setForm,
  ] = useState({
    username: "",
    password: "",
    "confirm-password": "",
  });
  const [error, setError] = useState("");

  function handleChange(e) {
    setForm({
      username,
      password,
      "confirm-password": confirmPassword,
      ...{ [e.target.name]: e.target.value.trim() },
    });
  }
  async function handleCreateAccount(e) {
    e.preventDefault();
    if (!username) return setError("Must include username");
    if (password !== confirmPassword) return setError("Passwords must Match");

    try {
      const res = await fetch("/api/auth/signup", {
        method: "POST",
        headers: {
          "content-type": "application/json",
        },
        body: JSON.stringify({ username, password }),
      });
      if (res.status === 200) {
        return router.push("/dashboard");
      }
      if (res.status === 400) {
        const { error: message } = await res.json();
        console.log(message);
        setError("Username is already taken.")
      }
    } catch (err) {

      console.log(err);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Budget Bud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/budgetbudlogo.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Budget Bud!
        </h1>

        <form
          className={[styles.card, styles.form].join(" ")}
          onSubmit={handleCreateAccount}
        >
          <label htmlFor="username">Username: </label>
          <input
            type="text"
            name="username"
            id="username"
            onChange={handleChange}
            value={username}
          />
          <label htmlFor="password">Password: </label>
          <input
            type="password"
            name="password"
            id="password"
            onChange={handleChange}
            value={password}
          />
          <label htmlFor="confirm-password">Confirm Password: </label>
          <input
            type="password"
            name="confirm-password"
            id="confirm-password"
            onChange={handleChange}
            value={confirmPassword}
          />
          <button>Submit</button>
          {error && <p>{error}</p>}
        </form>
        <Link href="/login">
          <p>Login instead?</p>
        </Link>
      </main>

      <footer className={styles.footer}>
        <p className={styles.footerLogo}>
          Budget Bud
          <span className={styles.logo}>
            <Image src="/budgetbudlogo.png" alt="Budget Bud Logo" width={25} height={28} />
          </span>
        </p>
      </footer>
    </div>
  );
}
